version: '3'
services:
  backend:
    build:
      context: ./jukebox-backend/recom_model
      dockerfile: Dockerfile  # Flask Dockerfile inside recom_model
    ports:
      - "5000:5000"
    volumes:
      - ./jukebox-backend/recom_model:/app  
    restart: unless-stopped

  node-server:
    build:
      context: .
      dockerfile: jukebox-backend/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
